#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

REPO_ROOT=""
REVIEW_ROOT=""
REVIEW_WORKTREE=""
BROWSER_PROFILE=""
BROWSER_BIN=""
BROWSER_KIND=""
FIREFOX_EXTENSION=""
BROWSER_PID=""
PR_NUMBER=""
PR_TITLE=""
PR_URL=""

cleanup() {
  if [[ -n "$BROWSER_PID" ]] && kill -0 "$BROWSER_PID" >/dev/null 2>&1; then
    kill "$BROWSER_PID" >/dev/null 2>&1 || true
    wait "$BROWSER_PID" >/dev/null 2>&1 || true
  fi
  if [[ -n "$REVIEW_WORKTREE" && -d "$REVIEW_WORKTREE" && -n "$REPO_ROOT" ]]; then
    git -C "$REPO_ROOT" worktree remove --force "$REVIEW_WORKTREE" >/dev/null 2>&1 || true
  fi
  if [[ -n "$REVIEW_ROOT" && -d "$REVIEW_ROOT" ]]; then
    rm -rf "$REVIEW_ROOT"
  fi
}
trap cleanup EXIT

find_browser() {
  local candidate
  if [[ "$BROWSER_KIND" == "firefox" ]]; then
    for candidate in firefox firefox-developer-edition; do
      if command -v "$candidate" >/dev/null 2>&1; then
        BROWSER_BIN=$(command -v "$candidate")
        return
      fi
    done
    return 1
  fi

  for candidate in chromium google-chrome google-chrome-stable brave-browser vivaldi; do
    if command -v "$candidate" >/dev/null 2>&1; then
      BROWSER_BIN=$(command -v "$candidate")
      return
    fi
  done
  return 1
}

prepare_firefox_extension() {
  local archives
  say "Building the Firefox package for this PR."
  (cd "$REVIEW_WORKTREE" && npm ci && npm run build:firefox)
  archives=("$REVIEW_WORKTREE"/dist/*-firefox.zip)
  if [[ ! -f "${archives[0]}" ]]; then
    warn "The Firefox extension package was not created."
    exit 1
  fi
  FIREFOX_EXTENSION="$REVIEW_ROOT/firefox-extension"
  mkdir -p "$FIREFOX_EXTENSION"
  unzip -q "${archives[0]}" -d "$FIREFOX_EXTENSION"
  "$BROWSER_BIN" -CreateProfile \
    "save-pinned-review-$PR_NUMBER $BROWSER_PROFILE" \
    >/dev/null
}

show_browser_setup() {
  if [[ "$BROWSER_KIND" == "firefox" ]]; then
    step "On about:debugging, click 'This Firefox'."
    step "Click 'Load Temporary Add-on'."
    step "Select: $FIREFOX_EXTENSION/manifest.json"
    step "Pin test tabs, then open Save Pinned Tabs from the toolbar."
  else
    step "On chrome://extensions, confirm Save Pinned Tabs is enabled."
    step "Pin test tabs, then open the extension from its toolbar icon."
  fi
}

launch_browser() {
  if [[ "$BROWSER_KIND" == "firefox" ]]; then

    "$BROWSER_BIN" \
      --no-remote \
      --new-instance \
      --profile "$BROWSER_PROFILE" \
      "about:debugging#/runtime/this-firefox" \
      >"$REVIEW_ROOT/browser.log" 2>&1 &
  else
    "$BROWSER_BIN" \
      --user-data-dir="$BROWSER_PROFILE" \
      --disable-extensions-except="$REVIEW_WORKTREE/src" \
      --load-extension="$REVIEW_WORKTREE/src" \
      chrome://extensions/ \
      >"$REVIEW_ROOT/browser.log" 2>&1 &
  fi
  BROWSER_PID=$!
  sleep 2
}

restart_browser() {
  step "Close every window in the isolated review browser."
  pause "Press Enter after the isolated browser has exited."
  wait "$BROWSER_PID" >/dev/null 2>&1 || true
  launch_browser
  if [[ "$BROWSER_KIND" == "firefox" ]]; then
    warn "Firefox removes temporary add-ons when it exits."
    show_browser_setup
    pause "Press Enter after reloading the temporary add-on."
  fi
}

show_review_steps() {
  case "$PR_NUMBER" in
    58)
      step "Pin two tabs, save them as a set, and enable Autoload."
      restart_browser
      step "Confirm exactly two pinned tabs were restored."
      step "Open DevTools in a separate window or open another popup-type window."
      step "Confirm the pinned tabs are not duplicated."
      ;;
    59)
      step "Open the extension Options page and select 'First browser window only'."
      restart_browser
      step "Open a second normal browser window; confirm it receives no Autoload tabs."
      step "Select 'Every new browser window', then open another normal window."
      step "Confirm the new window receives the Autoload set."
      ;;
    60)
      step "Save a set containing at least three pinned tabs."
      step "Add an unwanted pinned tab, then load the saved set."
      step "Confirm every restored tab, including the rightmost one, is pinned and compact."
      ;;
    61)
      step "With no pinned tabs, enter a set name and press Save."
      step "Confirm the popup says to pin at least one tab before saving."
      step "Repeat with the Save button on an existing set."
      ;;
    62)
      step "Create two saved sets, then restart the isolated browser."
      restart_browser
      step "Confirm both saved sets still show a Save button."
      step "Change the pinned tabs and use either row's Save button to update it."
      ;;
    63)
      step "Create a set and click Edit."
      step "Add, remove, reorder, and change URLs, then save and reopen the editor."
      step "Confirm the new list persisted."
      step "Enter javascript:alert(1) and confirm it is rejected."
      ;;
    64)
      step "Save a group, then add an unrelated pinned tab."
      step "Click Unload on the saved group."
      step "Confirm the group's tabs close and the unrelated pinned tab remains."
      ;;
    65)
      step "Rename a saved set and confirm its URLs and Autoload setting remain."
      step "Change the pinned tabs and click Save on the renamed set."
      step "Confirm no duplicate set appears."
      step "Reuse the old title for a new set and confirm both sets survive."
      ;;
    66)
      step "Save a group containing tabs A and B."
      step "Change the current pinned tabs to A and C, then click Append."
      step "Confirm the result is A, B, and C with no duplicate A."
      ;;
    68)
      step "Create two sets with one URL shared between them."
      step "Enable Autoload on both sets."
      restart_browser
      step "Confirm both sets load and the shared URL appears only once."
      ;;
    69)
      step "Save a title longer than 30 characters."
      step "Also save a title containing one long unbroken string."
      step "Confirm both titles remain complete, wrap, and keep their action buttons visible."
      ;;
    70)
      if [[ "$BROWSER_KIND" == "firefox" ]]; then
        warn "Firefox does not support Chromium's favicon cache API."
        step "Save a set, enable Autoload, and restart Firefox."
        restart_browser
        step "Confirm normal tab restoration still works without extension errors."
      else
        step "Visit two sites once so Chromium has their favicons, then save and enable Autoload."
        restart_browser
        step "Watch the tab strip during restoration and confirm cached icons appear promptly."
        step "Confirm the tabs themselves are not delayed while icons are fetched."
      fi
      ;;
    71)
      say "This PR changes tests only; no browser interaction is required."
      step "The wizard will run the Chromium suite five times."
      (cd "$REVIEW_WORKTREE" && npm ci && npx playwright test --repeat-each=5)
      ;;
    *)
      step "Read the PR description and exercise its stated behavior."
      step "Check the browser's extension-debugging page for errors."
      ;;
  esac
}

banner "Save Pinned Tabs manual review"

stage "Prerequisites"
for command in git gh npm; do
  if ! command -v "$command" >/dev/null 2>&1; then
    warn "Missing required command: $command"
    exit 1
  fi
done
if ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not authenticated. Run: gh auth login"
  exit 1
fi
ask BROWSER_KIND "Browser to review (chromium/firefox):"
case "$BROWSER_KIND" in
  chromium|firefox) ;;
  *)
    warn "Choose either chromium or firefox."
    exit 1
    ;;
esac
if [[ "$BROWSER_KIND" == "firefox" ]] && ! command -v unzip >/dev/null 2>&1; then
  warn "Firefox review requires unzip."
  exit 1
fi
if ! find_browser; then
  warn "No supported $BROWSER_KIND browser was found."
  exit 1
fi
REPO_ROOT=$(git rev-parse --show-toplevel)
say "Repository: $REPO_ROOT"
say "Browser: $BROWSER_BIN"
pause "Prerequisites are ready. Press Enter to continue."

stage "Choose pull request"
ask PR_NUMBER "PR number to review (58-71):"
if [[ ! "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
  warn "PR number must contain digits only."
  exit 1
fi
PR_TITLE=$(gh pr view "$PR_NUMBER" --json title --jq .title)
PR_URL=$(gh pr view "$PR_NUMBER" --json url --jq .url)
say "Selected: #$PR_NUMBER — $PR_TITLE"
open_url "$PR_URL"
pause "Press Enter after reading the PR description."

stage "Create isolated checkout"
REVIEW_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/save-pinned-review-${PR_NUMBER}-XXXXXX")
REVIEW_WORKTREE="$REVIEW_ROOT/worktree"
BROWSER_PROFILE="$REVIEW_ROOT/$BROWSER_KIND-profile"
git -C "$REPO_ROOT" fetch origin "pull/$PR_NUMBER/head"
git -C "$REPO_ROOT" worktree add --detach "$REVIEW_WORKTREE" FETCH_HEAD >/dev/null
if [[ "$BROWSER_KIND" == "firefox" && "$PR_NUMBER" != "71" ]]; then
  prepare_firefox_extension
fi
say "Checkout: $REVIEW_WORKTREE"
say "Profile: $BROWSER_PROFILE"

stage "Launch isolated browser"
if [[ "$PR_NUMBER" != "71" ]]; then
  launch_browser
  show_browser_setup
  note "This browser uses a disposable profile. It cannot affect your regular browser."
  pause "Press Enter when the extension popup is ready."
else
  say "Skipping browser launch for test-only PR #71."
fi

stage "Review feature"
show_review_steps
pause "Press Enter after completing the checks."

stage "Record result"
ask REVIEW_RESULT "Result (pass/fail/skip):"
ask REVIEW_NOTES "Notes (optional):"
say "Result: $REVIEW_RESULT"
if [[ -n "$REVIEW_NOTES" ]]; then say "Notes: $REVIEW_NOTES"; fi
if confirm "Post this result as a comment on PR #$PR_NUMBER?"; then
  gh pr comment "$PR_NUMBER" --body "Manual review: **$REVIEW_RESULT**

$REVIEW_NOTES"
  say "Posted review result to $PR_URL"
fi

stage "Clean up"
if [[ "$PR_NUMBER" != "71" ]]; then
  step "Close every isolated review-browser window."
  pause "Press Enter after the browser has exited."
fi
cleanup
trap - EXIT
say "Removed the temporary browser profile and Git worktree."

finish
